language: node_js
sudo: false
node_js:
- 8
install:
- npm install
script:
- npm run lint
- nyc npm test && nyc report --reporter=text-lcov | coveralls
services:
- postgresql
before_script:
- cd dbscripts
- psql -c 'create database telescopesdb;' -U postgres
- psql -c "\i ./testcreateandfill" telescopesdb postgres
- cd ..
