language: node_js
os: windows
sudo: false
node_js:
- 8
install:
- npm install
- npm install eslint
script:
- npm run lint
- nyc npm test && nyc report --reporter=text-lcov | coveralls
services:
- postgresql
before_script:
- psql -c 'create database telescopesdb;' -U postgres
- psql -c "\i ./dbscripts/createtables.sql" telescopesdb postgres
deploy:
  provider: heroku
  api_key:
    secure: 6lWcKmgoLpNx21HCHBOVD4zAjzEKv/SqsTUe1NbMYFDs47WIqBHlPs6E3ZB2c6+6sxxcMengQXNpi5uEwaXY2Nn/aGATJO8Nn2sk5dcujAb6mkfq/Esd7VtgGY9IAiljeteEpQ2UYzGMaPVmhTbxRlOS2n+AawUz3Lk9s7uLXcaRTQ23ZcSh7UnDVEaT9o70wUzSaJXUbikC1mSKPEmV95x6I8vLUWYBu/rt5k8SCJPOVhwqBD7GMMSYRaB2bOTokEPVX86ZkD40e4SdK/GmZQCDJLGStUeYmtHE3ACULBuEjt2zqdk8XSpNQQjI0p3sDz6OKqzjPEK73pfEAPOuiFC+Id3iBnWA2dZ1osNdsNC0pAs2iCpdge1Ra389kttndLw7LcIIn0H2Dzzyh9Ik8ge5jjxvjI8BAYsuf3G2DpGPew62vVigxypPU+WsAxtF1X18xaCsXQA2s15c9oS2KP135NXOw7SWu+g8wa6KPiw56oPe5tLJBaXTxz5J1kZrZt2e76cdNeVJtAeekNw85MX8zlW9Iw33pdAlFWBjdRmF1Qw42xb01nsMYLxyFPyx+TKBllHMV7EDMH7ztdrIZ+zn2l8/hVijFmXLJx8XL9kOS/l6AyW/zTSily4LPjWh3Z5op5xu4GdHURqrXWbe0VPbc2dS4QWUCRqGQ8kPHEk=
