DROP TYPE IF EXISTS TELESCOPETYPE CASCADE;

CREATE TYPE TELESCOPETYPE AS ENUM(
	'катадиоптрический',
	'рефлектор',
	'рефрактор'
);

DROP TABLE IF EXISTS Telescopes CASCADE;

CREATE TABLE Telescopes(
	TelescopeID SERIAL PRIMARY KEY,
	TelescopeName TEXT NOT NULL UNIQUE,
	TelescopeType TELESCOPETYPE NOT NULL,
	TelescopeInfo TEXT  NOT NULL DEFAULT '',
	City TEXT NOT NULL DEFAULT 'Москва',
	Country TEXT NOT NULL DEFAULT 'Россия'
);

DROP TYPE IF EXISTS USERTYPE CASCADE;

CREATE TYPE USERTYPE AS ENUM(
	'user',
	'admin'
);

DROP TABLE IF EXISTS Users CASCADE;

CREATE TABLE Users(
	UserID SERIAL PRIMARY KEY,
	Login TEXT NOT NULL CHECK(Login <> '') UNIQUE,
	Email TEXT NOT NULL  CHECK(Email <> '') UNIQUE,
	Password TEXT NOT NULL 
		CHECK(length(Password) >= 6 AND length(Password) <= 30),
	UserInfo TEXT NOT NULL DEFAULT '',
	UserRole USERTYPE NOT NULL DEFAULT 'user',
	Avatar TEXT NOT NULL DEFAULT '/public/images/userphoto/defaultuseravatar.png'
);

DROP TABLE IF EXISTS Objects CASCADE;

CREATE TABLE Objects(
	ObjectID SERIAL PRIMARY KEY,
	ObjectName TEXT NOT NULL CHECK(ObjectName <> '')UNIQUE,
	H REAL NOT NULL
		CHECK (H  >= -90.0 AND H  <= 90.0),
	A REAL NOT NULL
		CHECK (A  >= 0.0 AND A  <= 360.0),
	Info TEXT DEFAULT ''
);

DROP TABLE IF EXISTS Visibility CASCADE;

CREATE TABLE Visibility(
	VisibilityID SERIAL PRIMARY KEY,
	TelescopeID INTEGER NOT NULL REFERENCES Telescopes(TelescopeID) ON DELETE CASCADE,
	ObjectID INTEGER NOT NULL REFERENCES Objects(ObjectID) ON DELETE CASCADE,
	UNIQUE (TelescopeID, ObjectID)
);

DROP TYPE IF EXISTS REQUESTSTATUSTYPE CASCADE;

CREATE TYPE REQUESTSTATUSTYPE AS ENUM(
	'принят',
	'выполнен'
);

DROP TABLE IF EXISTS Requests CASCADE;

CREATE TABLE Requests(
	RequestID SERIAL PRIMARY KEY,
	UserID INTEGER NOT NULL REFERENCES Users(UserID)
		ON DELETE CASCADE,
	TelescopeID INTEGER NOT NULL REFERENCES Telescopes(TelescopeID) ON DELETE CASCADE,
	ObjectID INTEGER NOT NULL REFERENCES Objects(ObjectID) ON DELETE CASCADE,
	CreateDate TIMESTAMP NOT NULL DEFAULT NOW(),
	RequestStatus REQUESTSTATUSTYPE NOT NULL DEFAULT 'принят'
);

DROP TABLE IF EXISTS Astrophotographies CASCADE;

CREATE TABLE Astrophotographies(
	AstrophotographyID SERIAL PRIMARY KEY,
	AstrophotographyPath TEXT NOT NULL UNIQUE,
	UserID INTEGER REFERENCES Users(UserID)
		ON DELETE SET NULL,
	RequestID  INTEGER REFERENCES Requests(RequestID) ON DELETE SET NULL,
	CreateDate TIMESTAMP NOT NULL DEFAULT NOW()
);
